### PR TITLE
microbit.org-style header as requested by Jonny

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
Links to microbit home page.

Draft for the moment. I'll review with Jonny on Monday.

### CODE REVIEW

**Comment by microbit-matt-hillsdon** [comment]
Output of `npm run test` for easy of demo.

[demo.zip](https://github.com/lancaster-university/codal-microbit-v2/files/6639327/demo.zip)

**Comment by microbit-matt-hillsdon** [comment]
CC @jaustin for review

**Comment by jaustin** [comment]
I'm happy with the visuals of this, seems fine when I move aside the js/css too. @microbit-matt-hillsdon do you want more than a visial ACK?

**Comment by finneyj** [comment]
thanks @microbit-matt-hillsdon!

**Pull request merged**
