### PR TITLE
NRF52LEDMatrix::rotateTo

### PR DESCRIPTION
**Pull request by martinwork**
Implements NRF52LEDMatrix::rotateTo. Demo hex: [HelloRotate.zip](https://github.com/lancaster-university/codal-microbit-v2/files/9485105/HelloRotate.zip)
```
#include "MicroBit.h"

MicroBit uBit;


void setRotationForGesture( uint16_t gesture)
{
  switch ( gesture)
  {
    case MICROBIT_ACCELEROMETER_EVT_TILT_UP:
      uBit.display.rotateTo(MICROBIT_DISPLAY_ROTATION_0);
      break;
    case MICROBIT_ACCELEROMETER_EVT_TILT_RIGHT:
      uBit.display.rotateTo(MICROBIT_DISPLAY_ROTATION_90);
      break;
    case MICROBIT_ACCELEROMETER_EVT_TILT_DOWN:
      uBit.display.rotateTo(MICROBIT_DISPLAY_ROTATION_180);
      break;
    case MICROBIT_ACCELEROMETER_EVT_TILT_LEFT:
      uBit.display.rotateTo(MICROBIT_DISPLAY_ROTATION_270);
      break;
  }
}


void onGesture( MicroBitEvent e)
{
  switch ( e.value)
  {
    case MICROBIT_ACCELEROMETER_EVT_TILT_UP:
    case MICROBIT_ACCELEROMETER_EVT_TILT_DOWN:
    case MICROBIT_ACCELEROMETER_EVT_TILT_LEFT:
    case MICROBIT_ACCELEROMETER_EVT_TILT_RIGHT:
      setRotationForGesture( e.value);
      break;
  }
}


void forever()
{
    while (true)
    {
      uBit.display.scroll("HELLO WORLD");
    }
}


int main()
{
    uBit.init();

    uBit.messageBus.listen( MICROBIT_ID_GESTURE, 0, onGesture);

    setRotationForGesture( uBit.accelerometer.getGesture());

    create_fiber( forever);

    release_fiber();
    return 0;
}

```

### CODE REVIEW

**Comment by finneyj** [comment]
ooh, thanks @martinwork. I always liked this on v1! 

Looks good to me.

**Comment by martinwork** [comment]
@finneyj Phew! It would be good to get this merged soon, as @bsiever has an extension to expose it in MakeCode.

**Comment by bsiever** [comment]
Thanks @finneyj!  My first approach suffered from a CODAL memory leak due to reallocation of `MicroBitDisplay` (leak due to `new` [here](https://github.com/lancaster-university/codal-microbit-v2/blob/111e4cf829fdfea25e301375643d1bad71fb7070/source/MicroBitDisplay.cpp#L43%C2%A0)).   My workaround was an abuse of `new` and `delete` to be able to cleanup the lost memory.

Reallocating the `MicroBitDisplay` was a hack that didn't behave as smoothly as the `rotateTo()` does.  Very happy to have a better option!  (Thanks @martinwork!)

**Comment by finneyj** [comment]
Can you schedule this merge this in for the next release please @JohnVidler?

**Comment by JohnVidler** [comment]
Looks good to me, happy to merge :) Thanks @martinwork and @bsiever

**Pull request merged**
