### PR TITLE
MicroBitBLEManager - Move MICROBIT_BLE_MAXIMUM_BONDS to MicroBitConfig

### PR DESCRIPTION
**Pull request by martinwork**
See https://github.com/lancaster-university/codal-microbit-v2/issues/289.

I can't think what I can do to test this.

### CODE REVIEW

**Comment by microbit-carlos** [comment]
Yes please, let's make it a built time config option 👍

We should aim to have all flag defaults in `MicroBitConfig.h`, so let's move it there (looks like it's already identified as a BLE config not ported there yet, I think it's fine to start with this one, even if we don't have the others there yet).

For the DAL vs CODAL config in MakeCode, I thought they are separated?

```json
{
    "yotta": {
        "config": {
            "codal": {
                "MICROBIT_BLE_MAXIMUM_BONDS": 20,
            },
            "microbit-dal": {
            }
        }
    }
}
```

**Comment by martinwork** [comment]
@microbit-carlos 
> For the DAL vs CODAL config in MakeCode, I thought they are separated?
Ah I did not know that!

**Comment by martinwork** [comment]
MakeCode project with settings edited to choose 15 bonds and create utility service
https://makecode.microbit.org/_KLihp9h8PXiu

**Review by carlosperate — APPROVED** [review]
LGTM 👍 

@finneyj any chance you could have a look at this one in case we can squeze it into today's tag?

**Comment by finneyj** [comment]
Thanks @carlosperate  @martinwork 

Looks good to me! This shouldn't change any default behaviour, but it does feel like we should see what happens if we set a value other than 4 :)  

As I recall, SoftDevice stores its bond data in a dedicate page of FLASH... so my guess is that we're good up until the point that page fills up. 

I'm happy for this to go in as it is low risk, but we should work out what the hard maximum is in due course, and ensure we're not creating undefined behviour by that page overflowing into other areas of FLASH etc.

**Comment by microbit-carlos** [comment]
Yeah, the plan is to be able to expose this a build-time config option, so that we can create a MakeCode project and test if we can store 30 bonds:
- https://github.com/lancaster-university/codal-microbit-v2/issues/289

As we don't have that many devices around, we can get some help testing from teachers and other volunteers, and for that having a MakeCode project to share with them would be quite handy.

**Comment by finneyj** [comment]
cool - thanks carlos. Sounds good!

**Comment by martinwork** [comment]
The bonds are stored by the Nordic SDK in it's FDS file system, for which we have reserved the minimum 2 pages.
https://github.com/martinwork/codal-microbit-nrf5sdk/blob/master/sdk_config/sdk_config.h#L967

I calculated that 20 is the absolute most that might fit without changing the memory map, but 20 might trigger garbage collection, so I suggested 15 as a safer bet. I would guess that exceeding the limit has been tested for 5 devices, but the FDS has never been filled.

**Pull request merged**
