### PR TITLE
Added definitions to match the Makecode effects parameters

### PR DESCRIPTION
**Pull request by JohnVidler**
As per the title, just a set of definitions for downstream languages to use.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Yes, this should work for MicroPython.

**Review by microbit-carlos — APPROVED** [review]
Ready to be merged 👍

**Comment by microbit-carlos** [comment]
Added to MakeCode in:
- https://github.com/microsoft/pxt-microbit/pull/5768

**Comment by dpgeorge** [comment]
Actually, this doesn't work for MicroPython because we use C and can't include a C++ header in C code...

**Pull request merged**
