### PR TITLE
Change datalog CSV download mime type from text/plain to text/csv

### PR DESCRIPTION
**Pull request by martinwork**
Relates to https://github.com/lancaster-university/codal-microbit-v2/issues/327.

### CODE REVIEW

**Comment by microbit-matt-hillsdon** [comment]
As things stand I think this PR will have no effect. See [this doc](https://github.com/lancaster-university/codal-microbit-v2/blob/master/resources/logfs/README.md) for how to convert `header.html` into a change to the C++ file that embeds it. I can do this if needed.

I'm a bit puzzled as to why I didn't do this in the first place so I'd like to re-run some testing to make sure it doesn't make anything worse. It saves me two bytes in the header HTML which were very hard to come by! I'll try to do that this week.

**Comment by martinwork** [comment]
Thanks @microbit-matt-hillsdon

**Comment by microbit-carlos** [comment]
I've pushed a commit updating the MicroBitLog.cpp file and it's tripled the available free space from 1 byte to 3 🎉 🤣
@microbit-matt-hillsdon let us know once you've had a chance to run the test you had in mind and we can merge the PR 👍

**Comment by JohnVidler** [comment]
Looks good to me, lets get this merged in. 👍

**Comment by microbit-carlos** [comment]
@microbit-matt-hillsdon / @microbit-robert this PR has been merged to CODAL, it mostly sets the CSV mime type from `text/plain` to `text/csv`. Letting you know as I assume the same mime type should probably be applied to any other CSV downloads for iOS.

**Pull request merged**
